NUM_GPU=1
MAX_GPU_MEM=20GiB

python run_conv_exp1.py --output_file ./simulation_output/gender/male.json --input_file ./data/gender/male.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/gender/female.json --input_file ./data/gender/female.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2

python run_conv_exp1.py --output_file ./simulation_output/gender/teen.json --input_file ./data/gender/teen.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/gender/adult.json --input_file ./data/gender/adult.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/gender/middle-age.json --input_file ./data/gender/middle-age.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/gender/elderly.json --input_file ./data/gender/elderly.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2

python run_conv_exp1.py --output_file ./simulation_output/occupation/farmer.json --input_file ./data/occupation/farmer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/woodcutter.json --input_file ./data/occupation/woodcutter.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/fisherman.json --input_file ./data/occupation/fisherman.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/horticulturist.json --input_file ./data/occupation/horticulturist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/software_engineer.json --input_file ./data/occupation/software_engineer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/cybersecurity_specialist.json --input_file ./data/occupation/cybersecurity_specialist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/data_scientist.json --input_file ./data/occupation/data_scientist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/telecommunications_technician.json --input_file ./data/occupation/telecommunications_technician.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/investment_analyst.json --input_file ./data/occupation/investment_analyst.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/actuary.json --input_file ./data/occupation/actuary.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/insurance_claims_adjuster.json --input_file ./data/occupation/insurance_claims_adjuster.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/financial_advisor.json --input_file ./data/occupation/financial_advisor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/primary_school_teacher.json --input_file ./data/occupation/primary_school_teacher.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/university_professor.json --input_file ./data/occupation/university_professor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/vocational_trainer.json --input_file ./data/occupation/vocational_trainer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/special_education_teacher.json --input_file ./data/occupation/special_education_teacher.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/doctor.json --input_file ./data/occupation/doctor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/nurse.json --input_file ./data/occupation/nurse.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/physical_therapist.json --input_file ./data/occupation/physical_therapist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/psychologist.json --input_file ./data/occupation/psychologist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/actor.json --input_file ./data/occupation/actor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/musician.json --input_file ./data/occupation/musician.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/artist.json --input_file ./data/occupation/artist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_exp1.py --output_file ./simulation_output/occupation/writer.json --input_file ./data/occupation/writer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
