NUM_GPU=1
MAX_GPU_MEM=20GiB
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/farmer.json --input_file ./data/occupation/farmer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/woodcutter.json --input_file ./data/occupation/woodcutter.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/fisherman.json --input_file ./data/occupation/fisherman.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/horticulturist.json --input_file ./data/occupation/horticulturist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/software_engineer.json --input_file ./data/occupation/software_engineer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/cybersecurity_specialist.json --input_file ./data/occupation/cybersecurity_specialist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/data_scientist.json --input_file ./data/occupation/data_scientist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/telecommunications_technician.json --input_file ./data/occupation/telecommunications_technician.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/investment_analyst.json --input_file ./data/occupation/investment_analyst.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/actuary.json --input_file ./data/occupation/actuary.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/insurance_claims_adjuster.json --input_file ./data/occupation/insurance_claims_adjuster.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/financial_advisor.json --input_file ./data/occupation/financial_advisor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/primary_school_teacher.json --input_file ./data/occupation/primary_school_teacher.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/university_professor.json --input_file ./data/occupation/university_professor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/vocational_trainer.json --input_file ./data/occupation/vocational_trainer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/special_education_teacher.json --input_file ./data/occupation/special_education_teacher.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/doctor.json --input_file ./data/occupation/doctor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/nurse.json --input_file ./data/occupation/nurse.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/physical_therapist.json --input_file ./data/occupation/physical_therapist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/psychologist.json --input_file ./data/occupation/psychologist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/actor.json --input_file ./data/occupation/actor.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/musician.json --input_file ./data/occupation/musician.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/artist.json --input_file ./data/occupation/artist.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
python run_conv_3model_strategy.py --output_file ./simulation_output/occupation_strategy/writer.json --input_file ./data/occupation/writer.json --num-gpus $NUM_GPU --max-gpu-memory $MAX_GPU_MEM --cpu-offloading --user_temperature 0.4 --agent_temperature 0.2
